// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "우리시그노el",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "우리시그노el",
            targets: ["AppModule"],
            bundleIdentifier: "com.ark.MC1NoahArk",
            teamIdentifier: "2ZA4H6HG9F",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/globulus/swiftui-gif", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/twostraws/Subsonic", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftUIGIF", package: "swiftui-gif"),
                .product(name: "Subsonic", package: "subsonic")
            ],
            path: "."
        )
    ]
)